# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  app: 'chriskilinc'
  imageName: '$(app):$(tag)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'chriskilinc-docker'
    #     repository: 'chriskilinc/chriskilinc'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    - task: CmdLine@2
      inputs:
        script: yarn install
    - task: CmdLine@2
      inputs:
        script: yarn run build
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'